
#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_


//		CONFIGS FOR GROUPA PINS

//		DIRECTION IS DIO_u8OUTPUT OR DIO_u8INPUT
#define DIO_u8PA0_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PA1_DIR			DIO_u8PIN_INPUT
#define DIO_u8PA2_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PA3_DIR			DIO_u8PIN_INPUT
#define DIO_u8PA4_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PA5_DIR			DIO_u8PIN_INPUT
#define DIO_u8PA6_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PA7_DIR			DIO_u8PIN_INPUT

//		VALUE IS DIO_u8LOW OR DIO_u8HIGH IF PIN IS OUTPUT
//		VALUE IS DIO_u8FLOAT OR DIO_u8PULL_UP IF PIN IS INPUT
#define DIO_u8PA0_VALUE			DIO_u8PIN_LOW
#define DIO_u8PA1_VALUE			DIO_u8FLOAT
#define DIO_u8PA2_VALUE			DIO_u8PIN_LOW
#define DIO_u8PA3_VALUE			DIO_u8FLOAT
#define DIO_u8PA4_VALUE			DIO_u8PIN_HIGH
#define DIO_u8PA5_VALUE			DIO_u8PULL_UP
#define DIO_u8PA6_VALUE			DIO_u8PIN_HIGH
#define DIO_u8PA7_VALUE			DIO_u8PULL_UP





//		CONFIGS FOR GROUPB PINS

//		DIRECTION IS DIO_u8OUTPUT OR DIO_u8INPUT
#define DIO_u8PB0_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PB1_DIR			DIO_u8PIN_INPUT
#define DIO_u8PB2_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PB3_DIR			DIO_u8PIN_INPUT
#define DIO_u8PB4_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PB5_DIR			DIO_u8PIN_INPUT
#define DIO_u8PB6_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PB7_DIR			DIO_u8PIN_INPUT

//		VALUE IS DIO_u8LOW OR DIO_u8HIGH IF PIN IS OUTPUT
//		VALUE IS DIO_u8FLOAT OR DIO_u8PULL_UP IF PIN IS INPUT
#define DIO_u8PB0_VALUE			DIO_u8PIN_LOW
#define DIO_u8PB1_VALUE			DIO_u8FLOAT
#define DIO_u8PB2_VALUE			DIO_u8PIN_LOW
#define DIO_u8PB3_VALUE			DIO_u8FLOAT
#define DIO_u8PB4_VALUE			DIO_u8PIN_HIGH
#define DIO_u8PB5_VALUE			DIO_u8PULL_UP
#define DIO_u8PB6_VALUE			DIO_u8PIN_HIGH
#define DIO_u8PB7_VALUE			DIO_u8PULL_UP




//		CONFIGS FOR GROUPC PINS

//		DIRECTION IS DIO_u8OUTPUT OR DIO_u8INPUT
#define DIO_u8PC0_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PC1_DIR			DIO_u8PIN_INPUT
#define DIO_u8PC2_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PC3_DIR			DIO_u8PIN_INPUT
#define DIO_u8PC4_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PC5_DIR			DIO_u8PIN_INPUT
#define DIO_u8PC6_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PC7_DIR			DIO_u8PIN_INPUT

//		VALUE IS DIO_u8LOW OR DIO_u8HIGH IF PIN IS OUTPUT
//		VALUE IS DIO_u8FLOAT OR DIO_u8PULL_UP IF PIN IS INPUT
#define DIO_u8PC0_VALUE			DIO_u8PIN_LOW
#define DIO_u8PC1_VALUE			DIO_u8FLOAT
#define DIO_u8PC2_VALUE			DIO_u8PIN_LOW
#define DIO_u8PC3_VALUE			DIO_u8FLOAT
#define DIO_u8PC4_VALUE			DIO_u8PIN_HIGH
#define DIO_u8PC5_VALUE			DIO_u8PULL_UP
#define DIO_u8PC6_VALUE			DIO_u8PIN_HIGH
#define DIO_u8PC7_VALUE			DIO_u8PULL_UP




//		CONFIGS FOR GROUPD PINS

//		DIRECTION IS DIO_u8OUTPUT OR DIO_u8INPUT
#define DIO_u8PD0_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PD1_DIR			DIO_u8PIN_INPUT
#define DIO_u8PD2_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PD3_DIR			DIO_u8PIN_INPUT
#define DIO_u8PD4_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PD5_DIR			DIO_u8PIN_INPUT
#define DIO_u8PD6_DIR			DIO_u8PIN_OUTPUT
#define DIO_u8PD7_DIR			DIO_u8PIN_INPUT

//		VALUE IS DIO_u8LOW OR DIO_u8HIGH IF PIN IS OUTPUT
//		VALUE IS DIO_u8FLOAT OR DIO_u8PULL_UP IF PIN IS INPUT
#define DIO_u8PD0_VALUE			DIO_u8PIN_LOW
#define DIO_u8PD1_VALUE			DIO_u8FLOAT
#define DIO_u8PD2_VALUE			DIO_u8PIN_LOW
#define DIO_u8PD3_VALUE			DIO_u8FLOAT
#define DIO_u8PD4_VALUE			DIO_u8PIN_HIGH
#define DIO_u8PD5_VALUE			DIO_u8PULL_UP
#define DIO_u8PD6_VALUE			DIO_u8PIN_HIGH
#define DIO_u8PD7_VALUE			DIO_u8PULL_UP


#endif
